#AntiCheat configuration file
#Please report any bugs: http://dev.bukkit.org/server-mods/anticheat/

Logging:
  Log to console: false
  
XRay:
  Log xray stats: true

Events: 
  #Valid events = NONE,WARN,KICK,BAN
  Level Medium: WARN
  Level High: KICK